#### general settings
name: Dual_Path_RNN
use_tb_logger: true
num_spks: 2
#### datasets
datasets:
  train:
    video_path: '../../../LRS3/pretrain'
    n_samples: 10000
    video_features_path: '../../../LRS3/pretrain_a_video_features'
    noise_path: '../../../wham_noise/wham_noise/cv'
    deterministic: true
    cache_path: 'T2'
    batch_size: 8


  val:
    video_path: '../../../LRS3/pretrain'
    n_samples: 2000
    video_features_path: '../../../LRS3/pretrain_a_video_features'
    noise_path: '../../../wham_noise/wham_noise/cv'
    deterministic: true
    cache_path: 'V2'
    batch_size: 8
  
  
  dataloader_setting:
    shuffle: true
  
  audio_setting:
    sample_rate: 8000
  
  video_setting:
    fps: 25

  duration: 2

#### network structures
Dual_Path_RNN:
  in_channels: 256
  out_channels: 64 
  hidden_channels: 128
  kernel_size: 2
  video_kernel_size: 8
  upsample_size: 15999
  rnn_type: LSTM
  norm: ln
  dropout: 0
  bidirectional: true
  num_layers: 6
  K: 250
  num_spks: 2

#### training settings: learning rate scheme, loss
train:
  epoch: 5
  early_stop: 5
  path: checkpoints
  gpuid: [0]
  distributed: true

#### Optimizer settings
optim:
  name: Adam   ### Adam, RMSprop, SGD
  lr: !!float 5e-4
  momentum: 0
  weight_decay: 0
  clip_norm: 5

#### scheduler settings
scheduler:
  min_lr: !!float 1e-8
  patience: 2
  factor: 0.5

#### Resume training settings
resume:
  state: True
  path: checkpoints/Dual_Path_RNN/last.pt


#### logger
logger:
  name: DPCL
  path: checkpoints
  screen: false
  tofile: true
  tensorboard: true
  print_freq: 10
  